name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: docker pull nayandevdocker/angular-16-client:latest
    - name: Delete Old docker container
      run: docker rm -f angular-16-client-container || true
    - name: Run Docker Container
      run: docker run -d -p 4200:4200 --name angular-16-client-container nayandevdocker/angular-16-client
